-
  job: PublishToBintray
  pool:
      vmImage: 'ubuntu-16.04'
  steps:
      - bash: |
            ./deployToBintray.sh
            ./mvnw verify -DskipTests
            cd build/com.liferay.ide-repository
            curl -O -L --retry 3 https://github.com/sormuras/bach/raw/master/install-jdk.sh
            set -ev
            source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu8.38.0.13-ca-jdk8.0.212-linux_x64.tar.gz
        displayName: Build
        env:
            BINTRAY_API_KEY: $(BINTRAY_API_KEY)
            BINTRAY_USER: $(BINTRAY_USER)
jobs:

pr: none

    trigger:
        - master